window.SUBMISSION_TOOL_DATA = {
  defaultState: {
    caseName: '',
    caseNote: '',
    stage: 'phd',
    strategy: 'balanced',
    cnExperience: 'none',
    ssciExperience: 'none',
    advisorSupport: 'uncertain',
    funding: 'none',
    title: '',
    abstract: '',
    keywords: '',
    language: 'zh',
    length: '',
    articleType: 'theory',
    region: 'global',
    themes: ['great-power', 'global-governance'],
    methods: ['conceptual', 'case-study']
  },
  demoState: {
    caseName: '技术竞争与中美危机管控',
    caseNote: '示例稿，适合演示中文核心和 SSCI 路线如何同时保留。',
    stage: 'phd',
    strategy: 'balanced',
    cnExperience: 'none',
    ssciExperience: 'none',
    advisorSupport: 'uncertain',
    funding: 'some',
    title: '技术竞争如何重塑中美危机管控的制度空间？',
    abstract:
      '本文围绕中美技术竞争背景下危机管控机制的制度演化展开讨论。文章认为，技术竞争并未简单削弱危机管控，而是通过改变威慑结构、信息传递方式和联盟协调机制，重塑了危机管控的议题边界与制度空间。文章首先梳理危机管控与安全困境研究中的既有理论，随后以人工智能、半导体和军民两用技术治理为例，分析技术竞争如何影响中美在热线、规则磋商和风险沟通中的互动逻辑。本文采用案例比较与过程追踪相结合的方法，试图解释为何某些议题出现有限合作，而另一些议题则陷入制度锁定。文章最后提出，对中美关系的研究若仅停留在战略竞争叙事，将难以把握新兴技术条件下危机稳定与制度建构之间的张力。',
    keywords: '中美关系, 技术竞争, 危机管控, 国际秩序, 人工智能治理',
    language: 'zh',
    length: '16500',
    articleType: 'qualitative',
    region: 'china-us',
    themes: ['great-power', 'security', 'technology', 'international-order'],
    methods: ['case-study', 'process-tracing', 'conceptual']
  },
  themeCatalog: [
    { id: 'theory', label: '国际关系理论' },
    { id: 'great-power', label: '大国关系 / 中美' },
    { id: 'global-governance', label: '全球治理 / 国际组织' },
    { id: 'security', label: '安全研究 / 战略' },
    { id: 'china-diplomacy', label: '中国外交' },
    { id: 'asia-pacific', label: '亚太 / 印太' },
    { id: 'regional-study', label: '国别与区域' },
    { id: 'international-order', label: '国际秩序' },
    { id: 'political-economy', label: '国际政治经济' },
    { id: 'global-south', label: '全球南方' },
    { id: 'technology', label: '科技与全球治理' },
    { id: 'history', label: '历史 / 思想史' },
    { id: 'foreign-policy', label: '外交政策分析' }
  ],
  methodCatalog: [
    { id: 'conceptual', label: '概念 / 理论建构' },
    { id: 'case-study', label: '案例研究' },
    { id: 'process-tracing', label: '过程追踪 / 机制分析' },
    { id: 'discourse', label: '话语 / 文本分析' },
    { id: 'historical', label: '历史 / 档案材料' },
    { id: 'quantitative', label: '量化 / 数据分析' },
    { id: 'policy-analysis', label: '政策分析' }
  ],
  themePatterns: [
    { id: 'great-power', patterns: ['中美', '中俄', '大国关系', 'great power', 'major power', 'china-us', 'us-china', 'strategic competition', '战略竞争'] },
    { id: 'global-governance', patterns: ['全球治理', 'global governance', '国际组织', '联合国', 'united nations', '多边主义', 'multilateral', 'global institution'] },
    { id: 'security', patterns: ['安全', 'security', '威慑', 'deterrence', 'alliance', '同盟', '军事', '军控', '危机', 'crisis', 'war', 'conflict'] },
    { id: 'china-diplomacy', patterns: ['中国外交', 'china foreign policy', '中国特色大国外交', '外交思想', '对外政策', 'diplomacy'] },
    { id: 'asia-pacific', patterns: ['亚太', '印太', 'indo-pacific', 'asia-pacific', '东亚', '东盟', 'asean'] },
    { id: 'regional-study', patterns: ['区域', '国别', 'middle east', '中东', 'europe', '欧洲', 'africa', '非洲', 'latin america', '拉美'] },
    { id: 'international-order', patterns: ['国际秩序', '世界秩序', 'international order', '秩序转型', 'hegemony', '霸权'] },
    { id: 'political-economy', patterns: ['贸易', 'trade', 'investment', '投资', 'currency', '货币', 'supply chain', '供应链', '经济安全', 'ipe'] },
    { id: 'theory', patterns: ['理论', 'theory', 'constructivism', '现实主义', '自由主义', '英国学派', 'ontology', 'ontological security', 'conceptual'] },
    { id: 'global-south', patterns: ['全球南方', 'global south', '南南合作', '发展中国家', 'developing countries'] },
    { id: 'technology', patterns: ['技术', 'technology', '人工智能', 'ai', 'cyber', '数据', 'digital', 'semiconductor', '芯片'] },
    { id: 'history', patterns: ['历史', '冷战', '史', 'historical', 'archive', '档案', '思想史'] },
    { id: 'foreign-policy', patterns: ['foreign policy', '外交政策', 'decision-making', '决策过程', '外交决策'] }
  ],
  journals: [
    {
      id: 'cn-sjjyzz',
      name: '世界经济与政治',
      track: 'cn',
      indexing: 'CSSCI / 北大核心',
      difficulty: 5,
      doctoralSoloFriendliness: 2,
      fundingPreference: 4,
      coauthorNorm: 'often',
      scopeTags: ['theory', 'great-power', 'global-governance', 'security', 'international-order', 'political-economy'],
      styles: ['theory', 'qualitative', 'historical'],
      methods: ['conceptual', 'case-study', 'process-tracing', 'historical'],
      regions: ['global', 'china-us', 'asia-pacific', 'global-south'],
      length: { min: 12000, max: 25000, unit: 'chars', confidence: 'high' },
      abstract: '官方征稿启事说明：摘要一般 400-500 字，关键词一般 5-6 个。',
      keywordsRange: [5, 6],
      titleGuideline: '中文题目建议控制在 20 字左右，强调问题意识。',
      reviewStyle: '匿名评审；理论密度和创新性门槛高。',
      fitNote: '适合国际关系理论、实证、历史与方法讨论并重的国际问题研究。',
      riskNote: '对博士独作不排斥，但更常见成熟选题与项目支撑。',
      sourceConfidence: 'official+community',
      sources: [
        { label: '中国社科院世界经济与政治杂志投稿指南', url: 'https://iwep.cssn.cn/cbw/cbw_xsqk/xsqk_sjjjyzz/xsqk_tgzn_1601/' }
      ]
    },
    {
      id: 'cn-gjzzyj',
      name: '国际政治研究',
      track: 'cn',
      indexing: 'CSSCI / 北大核心',
      difficulty: 4.8,
      doctoralSoloFriendliness: 2,
      fundingPreference: 3,
      coauthorNorm: 'neutral',
      scopeTags: ['theory', 'china-diplomacy', 'great-power', 'regional-study', 'history', 'international-order'],
      styles: ['theory', 'historical', 'qualitative'],
      methods: ['conceptual', 'historical', 'case-study', 'process-tracing'],
      regions: ['global', 'china-us', 'asia-pacific', 'other-region'],
      length: { min: 22000, max: 28000, unit: 'chars', confidence: 'high' },
      abstract: '官方说明研究论文每篇约 2.5 万字，附 200-300 字中英文摘要和 3-5 个关键词。',
      keywordsRange: [3, 5],
      titleGuideline: '适合较完整的长文结构，题目不宜过泛。',
      reviewStyle: '双向匿名评审，正文须去作者信息。',
      fitNote: '更适合问题意识明确、文献史与理论史处理扎实的长文。',
      riskNote: '若当前稿件不足 2 万字，通常需要扩充文献综述与论证层次。',
      sourceConfidence: 'official',
      sources: [
        { label: '国际政治研究官网', url: 'https://www.jis.pku.edu.cn/Zhushi1407/' },
        { label: '国际政治研究投稿须知整理', url: 'https://www.eshukan.com/bd_show.aspx?cid=1&id=2470' }
      ]
    },
    {
      id: 'cn-wjpl',
      name: '外交评论',
      track: 'cn',
      indexing: 'CSSCI / 北大核心',
      difficulty: 4.4,
      doctoralSoloFriendliness: 2.5,
      fundingPreference: 4,
      coauthorNorm: 'often',
      scopeTags: ['china-diplomacy', 'foreign-policy', 'global-governance', 'security', 'political-economy', 'regional-study'],
      styles: ['policy', 'qualitative', 'theory'],
      methods: ['policy-analysis', 'case-study', 'process-tracing', 'conceptual'],
      regions: ['global', 'china-us', 'asia-pacific', 'middle-east', 'other-region'],
      length: { min: 12000, max: 20000, unit: 'chars', confidence: 'low' },
      abstract: '建议准备中英文题目、摘要、关键词，并以期刊模板为准。',
      keywordsRange: [3, 5],
      titleGuideline: '偏好问题明确、政策含义清晰的题目。',
      reviewStyle: '在线系统投稿；正式要求以模板与最新系统说明为准。',
      fitNote: '适合中国外交、外交政策、国际战略与实践导向较强的稿件。',
      riskNote: '圈层竞争较强，导师合作与项目支撑在经验上更常见。',
      sourceConfidence: 'official+community',
      sources: [
        { label: '外交评论编辑中心', url: 'https://wjxy.cbpt.cnki.net/index.aspx?t=3' },
        { label: '外交评论投稿问答整理', url: 'https://www.xueshu.com/wjpl/wenda/02.html' }
      ]
    },
    {
      id: 'cn-gjlt',
      name: '国际论坛',
      track: 'cn',
      indexing: 'CSSCI / 北大核心',
      difficulty: 3.6,
      doctoralSoloFriendliness: 4,
      fundingPreference: 2,
      coauthorNorm: 'neutral',
      scopeTags: ['china-diplomacy', 'great-power', 'asia-pacific', 'regional-study', 'foreign-policy', 'global-governance'],
      styles: ['qualitative', 'policy', 'theory'],
      methods: ['case-study', 'policy-analysis', 'process-tracing', 'conceptual'],
      regions: ['global', 'china-us', 'asia-pacific', 'other-region'],
      length: { min: 10000, max: 15000, unit: 'chars', confidence: 'medium' },
      abstract: '社区整理常见要求：中英文摘要、关键词、作者简介齐备。',
      keywordsRange: [3, 5],
      titleGuideline: '适合较具体的议题切口，不必过于宏大。',
      reviewStyle: '脚注规范较重要，通常需要页下注。',
      fitNote: '对国际政治、区域国别、中外关系类博士稿较有现实性。',
      riskNote: '相对适合作为中文首投或稳妥备投。',
      sourceConfidence: 'community',
      sources: [
        { label: '国际论坛相关信息页', url: 'https://guojiluntan.xueshu.com/' },
        { label: '北外国际论坛编辑部活动信息', url: 'https://sird.bfsu.edu.cn/info/1063/3643.htm' }
      ]
    },
    {
      id: 'cn-gjgc',
      name: '国际观察',
      track: 'cn',
      indexing: 'CSSCI / 北大核心',
      difficulty: 3.8,
      doctoralSoloFriendliness: 3.5,
      fundingPreference: 2,
      coauthorNorm: 'neutral',
      scopeTags: ['global-governance', 'china-diplomacy', 'foreign-policy', 'political-economy', 'security', 'regional-study'],
      styles: ['qualitative', 'policy', 'theory'],
      methods: ['case-study', 'policy-analysis', 'process-tracing', 'conceptual'],
      regions: ['global', 'china-us', 'asia-pacific', 'europe', 'middle-east', 'other-region'],
      length: { min: 12000, max: 15000, unit: 'chars', confidence: 'medium' },
      abstract: '常见要求为 300 字左右中英文摘要和关键词。',
      keywordsRange: [3, 5],
      titleGuideline: '更适合国际问题研究中的中等篇幅专题文章。',
      reviewStyle: '引注和脚注体例要先对齐近年已发文章。',
      fitNote: '在国际政治、世界经济、外交政策、区域议题之间覆盖面较广。',
      riskNote: '对青年作者较不封闭，但依然需要问题意识清楚。',
      sourceConfidence: 'community',
      sources: [
        { label: '国际观察投稿要求整理', url: 'https://www.qikan58.cn/qikan_detail.jsp?id=15269' },
        { label: '国际观察信息页', url: 'https://gjgc.mlunwen.com/' }
      ]
    },
    {
      id: 'cn-ddyt',
      name: '当代亚太',
      track: 'cn',
      indexing: 'CSSCI / 北大核心',
      difficulty: 4.6,
      doctoralSoloFriendliness: 2.5,
      fundingPreference: 3,
      coauthorNorm: 'neutral',
      scopeTags: ['asia-pacific', 'great-power', 'security', 'international-order', 'political-economy', 'global-south'],
      styles: ['qualitative', 'theory', 'policy'],
      methods: ['case-study', 'process-tracing', 'policy-analysis', 'conceptual'],
      regions: ['asia-pacific', 'china-us', 'global-south', 'other-region'],
      length: { min: 15000, max: 22000, unit: 'chars', confidence: 'low' },
      abstract: '常见要求为中英文题目、摘要、关键词，摘要约 120-300 字。',
      keywordsRange: [3, 8],
      titleGuideline: '亚太、印太、周边安全与区域秩序题材更有优势。',
      reviewStyle: '在线投稿；格式体例与图表规范较严格。',
      fitNote: '适合亚太区域、大国互动、区域秩序与经济安全相关稿件。',
      riskNote: '若非亚太主题，不建议硬投。',
      sourceConfidence: 'community',
      sources: [
        { label: '当代亚太投稿要求整理', url: 'https://oa.qikanv.com/qikan/show/id/6140' },
        { label: '当代亚太信息页', url: 'https://www.lefabiao.com/ddyt/' }
      ]
    },
    {
      id: 'en-int-affairs',
      name: 'International Affairs',
      track: 'ssci',
      indexing: 'SSCI',
      difficulty: 5,
      doctoralSoloFriendliness: 1.5,
      fundingPreference: 3,
      coauthorNorm: 'neutral',
      scopeTags: ['theory', 'great-power', 'global-governance', 'security', 'international-order', 'political-economy', 'foreign-policy'],
      styles: ['theory', 'policy', 'qualitative'],
      methods: ['conceptual', 'case-study', 'policy-analysis', 'process-tracing'],
      regions: ['global', 'china-us', 'asia-pacific', 'europe', 'global-south', 'middle-east'],
      length: { min: 7000, max: 9000, unit: 'words', confidence: 'high' },
      abstract: '官方作者指南：研究论文通常为 7000-9000 词，摘要不超过 200 词。',
      keywordsRange: [5, 6],
      titleGuideline: '标题要国际读者可读，不宜只写中文语境内部概念。',
      reviewStyle: '国际读者导向强，强调理论与政策双重可读性，重统计模型的稿件通常不占优。',
      fitNote: '广覆盖的 IR 顶刊，政策与学术兼顾，但竞争极强。',
      riskNote: '对无 SSCI 经验作者通常属于冲刺项，不宜作为唯一首投。',
      sourceConfidence: 'official',
      sources: [
        { label: 'International Affairs author guidelines', url: 'https://academic.oup.com/ia/pages/Author_Guidelines' },
        { label: 'International Affairs high impact papers', url: 'https://academic.oup.com/ia/pages/top_cited_papers' }
      ]
    },
    {
      id: 'en-cjip',
      name: 'The Chinese Journal of International Politics',
      track: 'ssci',
      indexing: 'SSCI',
      difficulty: 4.8,
      doctoralSoloFriendliness: 2,
      fundingPreference: 3,
      coauthorNorm: 'neutral',
      scopeTags: ['theory', 'china-diplomacy', 'great-power', 'international-order', 'asia-pacific'],
      styles: ['theory', 'qualitative', 'historical'],
      methods: ['conceptual', 'process-tracing', 'historical', 'case-study'],
      regions: ['china-us', 'asia-pacific', 'global'],
      length: { min: 8000, max: 12000, unit: 'words', confidence: 'medium' },
      abstract: '需要英文摘要与规范参考文献；建议按 OUP 体系准备。',
      keywordsRange: [4, 6],
      titleGuideline: '适合理论问题与中国议题结合较紧的英文稿。',
      reviewStyle: '对理论与论证要求高，英文写作要非常干净。',
      fitNote: '中国议题、国际秩序、大国关系相关英文稿的高门槛冲刺刊。',
      riskNote: '虽然 IF 并非最高，但并不属于“练手友好型”。',
      sourceConfidence: 'official',
      sources: [
        { label: 'CJIP About page', url: 'https://academic.oup.com/cjip/pages/About' }
      ]
    },
    {
      id: 'en-irap',
      name: 'International Relations of the Asia-Pacific',
      track: 'ssci',
      indexing: 'SSCI',
      difficulty: 4.2,
      doctoralSoloFriendliness: 2.5,
      fundingPreference: 2,
      coauthorNorm: 'neutral',
      scopeTags: ['asia-pacific', 'theory', 'great-power', 'regional-study', 'international-order', 'security'],
      styles: ['theory', 'qualitative', 'historical'],
      methods: ['conceptual', 'case-study', 'historical', 'process-tracing'],
      regions: ['asia-pacific', 'china-us', 'global'],
      length: { min: 8000, max: 11000, unit: 'words', confidence: 'medium' },
      abstract: '英文摘要必备；亚太问题导向强。',
      keywordsRange: [4, 6],
      titleGuideline: '议题最好能明确指向 Asia-Pacific / Indo-Pacific。',
      reviewStyle: '亚太相关性是硬门槛之一。',
      fitNote: '如果你的英文稿明确嵌入亚太议题，比投泛 IR 期刊更现实。',
      riskNote: '非亚太议题不要强投。',
      sourceConfidence: 'official',
      sources: [
        { label: 'IRAP journal page', url: 'https://academic.oup.com/irap/' }
      ]
    },
    {
      id: 'en-pacific-review',
      name: 'The Pacific Review',
      track: 'ssci',
      indexing: 'SSCI',
      difficulty: 4.1,
      doctoralSoloFriendliness: 3,
      fundingPreference: 2,
      coauthorNorm: 'neutral',
      scopeTags: ['asia-pacific', 'great-power', 'security', 'political-economy', 'regional-study', 'foreign-policy'],
      styles: ['qualitative', 'policy', 'theory'],
      methods: ['case-study', 'process-tracing', 'policy-analysis', 'conceptual'],
      regions: ['asia-pacific', 'china-us', 'global-south'],
      length: { min: 8000, max: 10000, unit: 'words', confidence: 'high' },
      abstract: '英文摘要与关键词必备；投稿说明较清晰。',
      keywordsRange: [4, 6],
      titleGuideline: '亚太国际互动、印太区域政治、地区秩序类最匹配。',
      reviewStyle: '主题要清楚落在 Asia-Pacific politics，而非仅仅“与亚洲有关”。',
      fitNote: '对亚太、印太、中美竞争、区域秩序英文稿非常关键。',
      riskNote: '非区域聚焦稿件的通过率会明显下降。',
      sourceConfidence: 'official',
      sources: [
        { label: 'The Pacific Review about page', url: 'https://www.tandfonline.com/journals/rpre20/about-this-journal' }
      ]
    },
    {
      id: 'en-global-society',
      name: 'Global Society',
      track: 'ssci',
      indexing: 'SSCI',
      difficulty: 3.5,
      doctoralSoloFriendliness: 3.5,
      fundingPreference: 1,
      coauthorNorm: 'neutral',
      scopeTags: ['global-governance', 'international-order', 'global-south', 'political-economy', 'technology'],
      styles: ['theory', 'policy', 'qualitative'],
      methods: ['conceptual', 'policy-analysis', 'case-study', 'discourse'],
      regions: ['global', 'global-south', 'asia-pacific', 'other-region'],
      length: { min: 7000, max: 9000, unit: 'words', confidence: 'high' },
      abstract: '英文摘要与关键词必备。',
      keywordsRange: [4, 6],
      titleGuideline: '适合全球治理、规范、跨国议题和全球社会讨论。',
      reviewStyle: '跨学科友好，但需要国际化英文表达。',
      fitNote: '如果文章不是很硬核的 IR theory，而是全球治理 / 跨国议题，常比顶刊更现实。',
      riskNote: '若稿件只是国内政策综述，国际读者相关性会不足。',
      sourceConfidence: 'official',
      sources: [
        { label: 'Global Society journal overview', url: 'https://www.tandfonline.com/journals/cgsj19' }
      ]
    },
    {
      id: 'en-contemporary-politics',
      name: 'Contemporary Politics',
      track: 'ssci',
      indexing: 'SSCI',
      difficulty: 3.3,
      doctoralSoloFriendliness: 4,
      fundingPreference: 1,
      coauthorNorm: 'neutral',
      scopeTags: ['foreign-policy', 'political-economy', 'regional-study', 'global-governance', 'technology'],
      styles: ['qualitative', 'policy', 'quantitative'],
      methods: ['case-study', 'policy-analysis', 'quantitative', 'process-tracing'],
      regions: ['global', 'asia-pacific', 'europe', 'global-south', 'other-region'],
      length: { min: 7000, max: 9000, unit: 'words', confidence: 'high' },
      abstract: '摘要一般控制在 150-200 词附近，关键词 4-6 个。',
      keywordsRange: [4, 6],
      titleGuideline: '适合议题清楚、比较政治与国际议题交叉的英文稿。',
      reviewStyle: '比顶级 IR 刊更现实，适合作为 SSCI 首投训练场。',
      fitNote: '对初次做英文投稿的作者较友好，尤其是具备案例或政策材料的文章。',
      riskNote: '如果文章过于传统 IR theory，未必是最佳目标。',
      sourceConfidence: 'official',
      sources: [
        { label: 'Contemporary Politics about page', url: 'https://www.tandfonline.com/journals/ccpo20/about-this-journal' }
      ]
    },
    {
      id: 'en-international-politics',
      name: 'International Politics',
      track: 'ssci',
      indexing: 'SSCI',
      difficulty: 3.7,
      doctoralSoloFriendliness: 3.2,
      fundingPreference: 1,
      coauthorNorm: 'neutral',
      scopeTags: ['theory', 'international-order', 'security', 'great-power', 'history', 'foreign-policy'],
      styles: ['theory', 'qualitative', 'historical'],
      methods: ['conceptual', 'case-study', 'historical', 'process-tracing'],
      regions: ['global', 'china-us', 'asia-pacific', 'europe', 'other-region'],
      length: { min: 8000, max: 10000, unit: 'words', confidence: 'medium' },
      abstract: 'Springer 体系投稿，摘要通常 150-250 词。',
      keywordsRange: [4, 6],
      titleGuideline: '适合一般国际政治问题，而不要求必须锁定某一区域。',
      reviewStyle: '需要清楚的问题意识与国际文献对话。',
      fitNote: '对于有理论意识、但还不到顶刊门槛的英文稿，是相对合理的现实目标。',
      riskNote: '若英文表达尚不稳定，仍需较大语言打磨。',
      sourceConfidence: 'official+community',
      sources: [
        { label: 'Springer submission guidelines example', url: 'https://link.springer.com/journal/11186/submission-guidelines' },
        { label: 'International Politics journal homepage', url: 'https://link.springer.com/journal/41311' }
      ]
    }
  ]
};
